os: linux
language: python
matrix:
  include:
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.6 VENV=venv
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=3.7 VENV=venv
  - os: osx
    language: generic
    env: INSTALL_TYPE=macpython VERSION=2.7 VENV=venv
required: sudo
python:
  - "2.7"
  - "3.4"
  - "3.5"
before_install:
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then git clone https://github.com/MacPython/terryfy.git; source terryfy/travis_tools.sh; get_python_environment $INSTALL_TYPE $VERSION $VENV; fi
  - "export DISPLAY=:99.0"
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo systemctl start xvfb; fi
  - sleep 3
install:
  - python -m pip install -U pip
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo apt-get install python-tk python3-tk; fi
  - python -m pip install -U coverage codecov pillow pynput babel nose
script:
  - python -m pip install .
  - python -m nose
after_success:
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then coverage run nosetests; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then codecov; fi
